version: "3.8"

services:
  mysql-chatapp:
    container_name: mysql-chatapp
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: chatapp
    ports:
      - "3307:3306"
    volumes:
      - mysql-chatapp-data:/var/lib/mysql
    networks:
      springboot-chatapp-network:
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$MYSQL_ROOT_PASSWORD"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  springboot-chatapp:
    container_name: springboot-chatapp
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      mysql-chatapp:
        condition: service_healthy
    networks:
      springboot-chatapp-network:

networks:
  springboot-chatapp-network:
    driver: bridge

volumes:
  mysql-chatapp-data:
